#  ############################################################################# #
#  Author       : dmike
#  Date         : 2,October 2016
#  Description  : Principal Make file
#
#  Default KBUILD file that does not define only the language variable.
#  Setting it to 'cc'.
#
#  ############################################################################# #
languages := golang
install_language := golang
mode := color_
debug := @

project_name := cmath
src_root := m
dep_root := $(empty)

# ############################################################################## #
# Plugin variables definition
# ############################################################################## #
mod_name := com.github/dual-lab/crypto-math-cli

export mod_name

#  ############################################################################# #
#  Command definition.
#  ############################################################################# #
CC := gcc
LD := ld
RM := rm
MV := mv
MKDIR:= mkdir
AR:= ar
RANLIB:= ranlib
DOCKER:= docker
GIT:= git
GO:= go
INSMOD := insmod
RMMOD := rmmod

export CC LD RM MKDIR AR RANLIB DOCKER GIT GO INSMOD RMMOD 
