[package]
name = "crypto-math"
version = "0.1.0"
edition = "2018"
repository = "https://github.com/dual-lab/crypto-math"
authors = ["dual-lab@yandex.com"]

[[bin]]
name = "climath"
edition = "2018"
path = "src/main.rs"


# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
structopt = "0.3.21"
anyhow = "1.0.40"
log = "0.4.14"
exitcode = "1.1.2"
indicatif = "0.16.2"
